// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var MapRe$ReactTemplate = require("./MapRe.bs.js");
var TakeRe$ReactTemplate = require("./TakeRe.bs.js");
var DelayRe$ReactTemplate = require("./DelayRe.bs.js");
var FilterRe$ReactTemplate = require("./FilterRe.bs.js");
var ForEachRe$ReactTemplate = require("./ForEachRe.bs.js");

var delay = DelayRe$ReactTemplate.delay;

var filter = FilterRe$ReactTemplate.filter;

var forEach = ForEachRe$ReactTemplate.forEach;

var map = MapRe$ReactTemplate.map;

var take = TakeRe$ReactTemplate.take;

exports.delay = delay;
exports.filter = filter;
exports.forEach = forEach;
exports.map = map;
exports.take = take;
/* No side effect */
