// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var UtilsRe$ReactTemplate = require("../UtilsRe.bs.js");

function delay(time, source, start, sink) {
  var sourceTalkback = [/* Nothing */0];
  var finished = [false];
  var timeout = [/* None */0];
  if (start !== 0) {
    return /* () */0;
  } else {
    return Curry._2(source, /* Start */0, /* Talkback */Block.__(1, [(function (action, data) {
                      switch (action) {
                        case 0 : 
                            sourceTalkback[0] = data;
                            return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                                          return Curry._2(talk, action, data);
                                        }));
                        case 1 : 
                            timeout[0] = /* Some */[setTimeout((function () {
                                      if (finished[0]) {
                                        return 0;
                                      } else {
                                        return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                                                      return Curry._2(talk, action, data);
                                                    }));
                                      }
                                    }), time)];
                            return /* () */0;
                        case 2 : 
                            setTimeout((function () {
                                    return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                                                  return Curry._2(talk, /* End */2, /* Nothing */0);
                                                }));
                                  }), time);
                            return /* () */0;
                        
                      }
                    })]));
  }
}

exports.delay = delay;
/* No side effect */
