// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var UtilsRe$ReactTemplate = require("../UtilsRe.bs.js");

function filter(predicate, source, start, sink) {
  var talkback = [/* Nothing */0];
  if (start !== 0) {
    return /* () */0;
  } else {
    return Curry._2(source, /* Start */0, /* Talkback */Block.__(1, [(function (action, data) {
                      switch (action) {
                        case 0 : 
                            talkback[0] = data;
                            return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                                          return Curry._2(talk, action, data);
                                        }));
                        case 1 : 
                            if (typeof data === "number" || data.tag) {
                              return /* () */0;
                            } else if (Curry._1(predicate, data[0])) {
                              return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                                            return Curry._2(talk, action, data);
                                          }));
                            } else {
                              return UtilsRe$ReactTemplate.whenTalk(talkback[0], (function (talk) {
                                            return Curry._2(talk, /* Data */1, /* Nothing */0);
                                          }));
                            }
                        case 2 : 
                            return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                                          return Curry._2(talk, action, data);
                                        }));
                        
                      }
                    })]));
  }
}

exports.filter = filter;
/* No side effect */
