// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var UtilsRe$ReactTemplate = require("../UtilsRe.bs.js");

function forEach(operation, source) {
  var talkback = [/* Nothing */0];
  return Curry._2(source, /* Start */0, /* Talkback */Block.__(1, [(function (action, data) {
                    switch (action) {
                      case 0 : 
                          talkback[0] = data;
                          break;
                      case 1 : 
                          UtilsRe$ReactTemplate.whenContent(data, operation);
                          break;
                      case 2 : 
                          break;
                      
                    }
                    if (action >= 2) {
                      return /* () */0;
                    } else {
                      return UtilsRe$ReactTemplate.whenTalk(talkback[0], (function (talk) {
                                    return Curry._2(talk, /* Data */1, /* Nothing */0);
                                  }));
                    }
                  })]));
}

exports.forEach = forEach;
/* No side effect */
