// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var UtilsRe$ReactTemplate = require("../UtilsRe.bs.js");

function map(operator, source, start, sink) {
  var sourceTalkback = [/* Nothing */0];
  var talkback = /* Talkback */Block.__(1, [(function (action, _) {
          switch (action) {
            case 0 : 
                return /* () */0;
            case 1 : 
                return UtilsRe$ReactTemplate.whenTalk(sourceTalkback[0], (function (talk) {
                              return Curry._2(talk, /* Data */1, /* Nothing */0);
                            }));
            case 2 : 
                return UtilsRe$ReactTemplate.whenTalk(sourceTalkback[0], (function (talk) {
                              return Curry._2(talk, /* End */2, /* Nothing */0);
                            }));
            
          }
        })]);
  if (start !== 0) {
    return /* () */0;
  } else {
    return Curry._2(source, /* Start */0, /* Talkback */Block.__(1, [(function (action, data) {
                      switch (action) {
                        case 0 : 
                            sourceTalkback[0] = data;
                            return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                                          return Curry._2(talk, /* Start */0, talkback);
                                        }));
                        case 1 : 
                            if (typeof data === "number" || data.tag) {
                              return /* () */0;
                            } else {
                              var result = Curry._1(operator, data[0]);
                              return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                                            return Curry._2(talk, action, /* Content */Block.__(0, [result]));
                                          }));
                            }
                        case 2 : 
                            return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                                          return Curry._2(talk, /* End */2, /* Nothing */0);
                                        }));
                        
                      }
                    })]));
  }
}

exports.map = map;
/* No side effect */
