// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var SourcesRe$ReactTemplate = require("./Sources/SourcesRe.bs.js");
var ConsumersRe$ReactTemplate = require("./Consumers/ConsumersRe.bs.js");

var Type = 0;

var pausableInterval = SourcesRe$ReactTemplate.pausableInterval;

var fromList = SourcesRe$ReactTemplate.fromList;

var fromLazyList = SourcesRe$ReactTemplate.fromLazyList;

var generateId = SourcesRe$ReactTemplate.generateId;

var delay = ConsumersRe$ReactTemplate.delay;

var filter = ConsumersRe$ReactTemplate.filter;

var forEach = ConsumersRe$ReactTemplate.forEach;

var map = ConsumersRe$ReactTemplate.map;

var take = ConsumersRe$ReactTemplate.take;

exports.Type = Type;
exports.pausableInterval = pausableInterval;
exports.fromList = fromList;
exports.fromLazyList = fromLazyList;
exports.generateId = generateId;
exports.delay = delay;
exports.filter = filter;
exports.forEach = forEach;
exports.map = map;
exports.take = take;
/* No side effect */
