// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function whenTalk(call, cb) {
  if (typeof call === "number" || !call.tag) {
    return /* () */0;
  } else {
    Curry._1(cb, call[0]);
    return /* () */0;
  }
}

function whenContent(call, cb) {
  if (typeof call === "number" || call.tag) {
    return /* () */0;
  } else {
    Curry._1(cb, call[0]);
    return /* () */0;
  }
}

function mapContent(fn, content) {
  if (typeof content === "number" || content.tag) {
    return content;
  } else {
    return /* Content */Block.__(0, [Curry._1(fn, content[0])]);
  }
}

exports.whenTalk = whenTalk;
exports.whenContent = whenContent;
exports.mapContent = mapContent;
/* No side effect */
