// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var UtilsRe$ReactTemplate = require("../UtilsRe.bs.js");

function fromLazyList(list, start, sink) {
  if (start !== 0) {
    return /* () */0;
  } else {
    var index = [0];
    return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                  return Curry._2(talk, /* Start */0, /* Talkback */Block.__(1, [(function (action, _) {
                                    if (action !== 1) {
                                      return /* () */0;
                                    } else {
                                      var match = Belt_List.get(list, index[0]);
                                      if (match) {
                                        index[0] = index[0] + 1 | 0;
                                        return Curry._2(talk, /* Data */1, /* Content */Block.__(0, [match[0]]));
                                      } else {
                                        return Curry._2(talk, /* End */2, /* Nothing */0);
                                      }
                                    }
                                  })]));
                }));
  }
}

exports.fromLazyList = fromLazyList;
/* No side effect */
