// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var UtilsRe$ReactTemplate = require("../UtilsRe.bs.js");

function fromList(list, start, sink) {
  if (start !== 0) {
    return /* () */0;
  } else {
    var completed = [false];
    var running = [false];
    return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                  return Curry._2(talk, /* Start */0, /* Talkback */Block.__(1, [(function (action, _) {
                                    switch (action) {
                                      case 0 : 
                                          return /* () */0;
                                      case 1 : 
                                          if (!running[0] && !completed[0]) {
                                            running[0] = true;
                                            Belt_List.forEach(list, (function (item) {
                                                    return Curry._2(talk, /* Data */1, /* Content */Block.__(0, [item]));
                                                  }));
                                            return Curry._2(talk, /* End */2, /* Nothing */0);
                                          } else {
                                            return 0;
                                          }
                                      case 2 : 
                                          completed[0] = true;
                                          return /* () */0;
                                      
                                    }
                                  })]));
                }));
  }
}

exports.fromList = fromList;
/* No side effect */
