// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var UtilsRe$ReactTemplate = require("../UtilsRe.bs.js");

function generateId(start, sink) {
  if (start !== 0) {
    return /* () */0;
  } else {
    var index = [-1];
    return UtilsRe$ReactTemplate.whenTalk(sink, (function (talk) {
                  return Curry._2(talk, /* Start */0, /* Talkback */Block.__(1, [(function (action, _) {
                                    if (action !== 1) {
                                      return /* () */0;
                                    } else {
                                      index[0] = index[0] + 1 | 0;
                                      return Curry._2(talk, /* Data */1, /* Content */Block.__(0, [index[0]]));
                                    }
                                  })]));
                }));
  }
}

exports.generateId = generateId;
/* No side effect */
