// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var FromListRe$ReactTemplate = require("./FromListRe.bs.js");
var GenerateIdRe$ReactTemplate = require("./GenerateIdRe.bs.js");
var FromLazyListRe$ReactTemplate = require("./FromLazyListRe.bs.js");
var PausableIntervalRe$ReactTemplate = require("./PausableIntervalRe.bs.js");

var pausableInterval = PausableIntervalRe$ReactTemplate.pausableInterval;

var fromList = FromListRe$ReactTemplate.fromList;

var fromLazyList = FromLazyListRe$ReactTemplate.fromLazyList;

var generateId = GenerateIdRe$ReactTemplate.generateId;

exports.pausableInterval = pausableInterval;
exports.fromList = fromList;
exports.fromLazyList = fromLazyList;
exports.generateId = generateId;
/* No side effect */
