// Generated by BUCKLESCRIPT VERSION 3.2.0, PLEASE EDIT WITH CARE
'use strict';

var Wonka = require("/home/august/open-source/my-repos/reason-server/node_modules/wonka/src/wonka.js");

var example = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* :: */[
            6,
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

Wonka.forEach((function (x) {
        console.log(String(x));
        return /* () */0;
      }), (function (param) {
        return Wonka.map((function (x) {
                      return (x << 1);
                    }), (function (param) {
                      return Wonka.filter((function (x) {
                                    return x % 2 === 0;
                                  }), (function (param) {
                                    return Wonka.fromList(example, param);
                                  }), param);
                    }), param);
      }));

exports.example = example;
/*  Not a pure module */
